version: "3.9"
services:
  dev:
    image: marcpartensky/discord-bot:dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./cogs:/app/cogs
      - ./config:/app/config
      - ./models:/app/models
      - ./__main__.py:/app/__main__.py

  prod:
    image: marcpartensky/discord-bot:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
