version: "3.9"
services:
  discord-bot-dev:
    image: marcpartensky/discord-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./cogs:/app/cogs
      - ./config:/app/config
      - ./models:/app/models
      - ./__main__.py:/app/__main__.py
      - ~/.config:/root/.config
      - ~/Downloads/squashfs-root/usr/bin/nvim:/usr/bin/nvim

  discord-bot-prod:
    image: marcpartensky/discord-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
