version: "3.9"
services:
  discord-bot:
    image: marcpartensky/discord-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./cogs:/app/cogs
      - ./config:/app/config
      - ./models:/app/models


