version: "3.9"
services:
  discord-bot:
    image: marcpartensky/discord-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./cogs:/app/cogs
      - ./config:/app/config
      - ./models:/app/models
      - ./__main__.py:/app/__main__.py


