services:
  dev:
    image: marcpartensky/discord-bot:dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: alpine
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./discord_bot/cogs:/app/cogs
      - ./discord_bot/config:/app/config
      - ./discord_bot/models:/app/models
      - ./discord_bot/__main__.py:/app/__main__.py

  prod:
    image: marcpartensky/discord-bot:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      target: alpine
    env_file:
      - .env
