[project]
name = "discord-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.8.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
