name: Docker

on:
  push:
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update apt
      run: sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y
    - name: Install Python3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the tag
      run: echo "TAG::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: marcpartensky/discord-bot:$TAG

  test-python-versions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
      - name: Install requirements
        run: pip install -r requirements.txt -e .
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run the bot
        run: python __main__.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_PREFIX: ${{ secrets.DISCORD_PREFIX }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_MONGO_CLUSTER: discord-cluster-5ckni.mongodb.net/test
          DISCORD_MONGO_USERNAME: esclave
          DISCORD_MONGO_PASSWORD: esclave
          WOLFRAM_ALPHA_ID: fake
          DOCKER_API_URL: fake
      - name: Check api
        run: curl localhost:8000/live

